// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using ResourceAllocation.Domain.Models;
using ResourceAllocation.Infrastructure.EntityFramework;

#nullable disable

namespace ResourceAllocation.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903103848_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status", new[] { "cancelled", "confirmed", "expired", "held" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResourceAllocation.Domain.Models.Allocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<NpgsqlRange<DateTime>>("Period")
                        .HasColumnType("tsrange")
                        .HasColumnName("period");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<Status>("Status")
                        .HasColumnType("status")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_allocations");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("ix_allocations_resource_id");

                    b.ToTable("allocations", (string)null);
                });

            modelBuilder.Entity("ResourceAllocation.Domain.Models.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("type_id");

                    b.HasKey("Id")
                        .HasName("pk_resources");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_resources_type_id");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("ResourceAllocation.Domain.Models.ResourceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_resource_types");

                    b.ToTable("resource_types", (string)null);
                });

            modelBuilder.Entity("ResourceAllocation.Domain.Models.Allocation", b =>
                {
                    b.HasOne("ResourceAllocation.Domain.Models.Resource", "Resource")
                        .WithMany("Allocations")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_allocations_resources_resource_id");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("ResourceAllocation.Domain.Models.Resource", b =>
                {
                    b.HasOne("ResourceAllocation.Domain.Models.ResourceType", "Type")
                        .WithMany("Resources")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resources_resource_types_type_id");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ResourceAllocation.Domain.Models.Resource", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("ResourceAllocation.Domain.Models.ResourceType", b =>
                {
                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
